"""first commit

Revision ID: 78864af08bb7
Revises: 
Create Date: 2022-05-31 07:44:34.015528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78864af08bb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operate_records',
    sa.Column('record_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('operate_username', sa.String(length=20), nullable=False, comment='操作的用户'),
    sa.Column('operate_time', sa.DateTime(), nullable=True, comment='操作的时间'),
    sa.Column('operate_ip', sa.String(length=20), nullable=False, comment='操作的IP'),
    sa.Column('operate_type', sa.String(length=10), nullable=False, comment='操作类型'),
    sa.Column('operate_object', sa.String(length=30), nullable=False, comment='操作的对象'),
    sa.Column('operate_detail', sa.String(length=200), nullable=True, comment='操作的具体信息'),
    sa.PrimaryKeyConstraint('record_id'),
    comment='数据操作记录表'
    )
    op.create_index(op.f('ix_operate_records_operate_username'), 'operate_records', ['operate_username'], unique=False)
    op.create_index(op.f('ix_operate_records_record_id'), 'operate_records', ['record_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False, comment='用户id'),
    sa.Column('username', sa.String(length=20), nullable=False, comment='登陆用户名'),
    sa.Column('nick_name', sa.String(length=20), nullable=True, comment='昵称'),
    sa.Column('avatar', sa.String(length=200), nullable=True, comment='头像'),
    sa.Column('email', sa.String(length=30), nullable=False, comment='邮箱'),
    sa.Column('hashed_password', sa.String(length=200), nullable=False, comment='加密后的密码'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('creat_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='最后一次更新时间'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    comment='用户表'
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_operate_records_record_id'), table_name='operate_records')
    op.drop_index(op.f('ix_operate_records_operate_username'), table_name='operate_records')
    op.drop_table('operate_records')
    # ### end Alembic commands ###
